import Header from '../components/Header';

import '@/app/style/style.css'
import '@/app/style/header.css'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({children}) {
    return (
        <html lang='pt-br'>
            <body><Header />{children}</body>
        </html>
    )
}
